name: Checkstyle Analysis

on: [push, pull_request]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run checkstyle with reviewdog
        uses: asaasdev/checkstyle-action@master 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Yahan 'checkstyle_config' ki jagah 'configuration_file' likhein:
          configuration_file: checkstyle.xml
          reporter: github-pr-review
          level: warning
          filter_mode: nofilter
