name: Checkstyle Analysis

on: [push, pull_request]

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Humne version ko 'master' ya 'v1' par set kar diya hai jo hamesha chalta hai
      - name: Run checkstyle with reviewdog
        uses: asaasdev/checkstyle-action@master 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          filter_mode: added
